/**
 * OpenAPI demo
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateProductRequest } from '../model/models';
import { ErrorMessage } from '../model/models';
import { Product } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ProductServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createProductRequest 
     */
    createProduct(createProductRequest?: CreateProductRequest, extraHttpRequestParams?: any): Observable<Product>;

    /**
     * 
     * 
     * @param productId 
     */
    deleteProduct(productId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param productId 
     */
    getProduct(productId: number, extraHttpRequestParams?: any): Observable<Product>;

    /**
     * 
     * 
     */
    getProducts(extraHttpRequestParams?: any): Observable<Array<Product>>;

}
